jobs:
- name: test-git-job
  plan:
  - task: add-one
    config:
      platform: linux
      image_resource:
        type: mock
        source: {mirror_self: true}
      run:
        path: sh
        args:
        - -c
        - |
          echo "niteesh from script"
